// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	Gameid       pgtype.UUID
	Title        pgtype.Text
	Player1id    pgtype.UUID
	Player2id    pgtype.UUID
	Tournamentid pgtype.UUID
}

type Player struct {
	Userid       pgtype.UUID
	Username     string
	Usertag      string
	Passwordhash string
}

type Tournament struct {
	Tournamentid pgtype.UUID
	Entryfee     pgtype.Numeric
}
